//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URLShortener.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("URLShortener.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abandoned
        ///able
        ///absolute
        ///adorable
        ///adventurous
        ///academic
        ///acceptable
        ///acclaimed
        ///accomplished
        ///accurate
        ///aching
        ///acidic
        ///acrobatic
        ///active
        ///actual
        ///adept
        ///admirable
        ///admired
        ///adolescent
        ///adorable
        ///adored
        ///Advanced
        ///Afraid
        ///Affectionate
        ///Aged
        ///Aggravating
        ///Aggressive
        ///Agile
        ///Agitated
        ///Agonizing
        ///Agreeable
        ///Ajar
        ///Alarmed
        ///Alarming
        ///Alert
        ///Alienated
        ///Alive
        ///All
        ///Altruistic
        ///Amazing
        ///Ambitious
        ///Ample
        ///Amused
        ///Amusing
        ///Anchored
        ///Ancient
        ///Angelic
        ///Angry
        ///Anguished
        ///Animated
        ///Annual
        ///Another
        ///Antique
        ///Anxious
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjectives {
            get {
                return ResourceManager.GetString("Adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple
        ///Apricot
        ///Avocado
        ///Banana
        ///Bilberry
        ///Blackberry
        ///Blackcurrant
        ///Blueberry
        ///Boysenberry
        ///Currant
        ///Cherry
        ///Cherimoya
        ///Cloudberry
        ///Coconut
        ///Cranberry
        ///Cucumber
        ///CustardApple
        ///Damson
        ///Date
        ///DecaisneaFargesii
        ///Dragonfruit
        ///Durian
        ///Elderberry
        ///Feijoa
        ///Fig
        ///Goji berry
        ///Gooseberry
        ///Grape
        ///Raisin
        ///Grapefruit
        ///Guava
        ///Honeyberry
        ///Huckleberry
        ///Jabuticaba
        ///Jackfruit
        ///Jambul
        ///Jujube
        ///JuniperBerry
        ///Kiwifruit
        ///Kumquat
        ///Lemon
        ///Lime
        ///Loquat
        ///Longan
        ///Lychee
        ///Mango
        ///Marionberry
        ///Melon
        ///Cantaloupe
        ///Honeydew
        ///Watermelon
        ///Mi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
    }
}
